/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/grid/grid.module';
import * as import2 from '@angular/common';
class GridModuleInjector extends import0.ɵNgModuleInjector<import1.GridModule> {
  _CommonModule_0:import2.CommonModule;
  _GridModule_1:import1.GridModule;
  __NgLocalization_2:import2.NgLocaleLocalization;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_2():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_2 == null)) { (this.__NgLocalization_2 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_2;
  }
  createInternal():import1.GridModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._GridModule_1 = new import1.GridModule();
    return this._GridModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.GridModule)) { return this._GridModule_1; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const GridModuleNgFactory:import0.NgModuleFactory<import1.GridModule> = new import0.NgModuleFactory<any>(GridModuleInjector,import1.GridModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovSmVua2lucy93b3Jrc3BhY2UvX2VqMi1ncmlkLWNvbXBvbmVudHNfbWFzdGVyLTdMNU9KMkk2SFk1NExPU08yTVVaT1ZUTUlON1g2VEM2UVhWWFhEWFFKQ0JHWUxGUkxRMkEvdGhpcmQtcGFydHkvYW5ndWxhci9zcmMvZ3JpZC9ncmlkLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9KZW5raW5zL3dvcmtzcGFjZS9fZWoyLWdyaWQtY29tcG9uZW50c19tYXN0ZXItN0w1T0oySTZIWTU0TE9TTzJNVVpPVlRNSU43WDZUQzZRWFZYWERYUUpDQkdZTEZSTFEyQS90aGlyZC1wYXJ0eS9hbmd1bGFyL3NyYy9ncmlkL2dyaWQubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
