/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/grid/grid.component';
import * as import2 from '@syncfusion/ej2-grids/src/grid/actions/filter';
import * as import3 from '@syncfusion/ej2-grids/src/grid/actions/page';
import * as import4 from '@syncfusion/ej2-grids/src/grid/actions/selection';
import * as import5 from '@syncfusion/ej2-grids/src/grid/actions/sort';
import * as import6 from '@syncfusion/ej2-grids/src/grid/actions/group';
import * as import7 from '@syncfusion/ej2-grids/src/grid/actions/reorder';
import * as import8 from '@syncfusion/ej2-grids/src/grid/actions/row-reorder';
const styles_GridComponent:any[] = ([] as any[]);
export const RenderType_GridComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_GridComponent,
  data: {}
}
);
export function View_GridComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(2,([] as any[]),(null as any),(null as any));
}
function View_GridComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),2,'ej-grid',([] as any[]),(null as any),(null as any),(null as any),View_GridComponent_0,RenderType_GridComponent)),
    import0.ɵdid(3268608,(null as any),1,import1.GridComponent,[
      import0.ElementRef,
      [
        2,
        import2.Filter
      ]
      ,
      [
        2,
        import3.Page
      ]
      ,
      [
        2,
        import4.Selection
      ]
      ,
      [
        2,
        import5.Sort
      ]
      ,
      [
        2,
        import6.Group
      ]
      ,
      [
        2,
        import7.Reorder
      ]
      ,
      [
        2,
        import8.RowDD
      ]

    ]
    ,(null as any),(null as any)),
    import0.ɵqud(167772160,1,{childColumns: 0})
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const GridComponentNgFactory:import0.ComponentFactory<import1.GridComponent> = import0.ɵccf('ej-grid',import1.GridComponent,View_GridComponent_Host_0,{
  allowFiltering: 'allowFiltering',
  allowGrouping: 'allowGrouping',
  allowPaging: 'allowPaging',
  allowReordering: 'allowReordering',
  allowRowDragAndDrop: 'allowRowDragAndDrop',
  allowSelection: 'allowSelection',
  allowSorting: 'allowSorting',
  allowTextWrap: 'allowTextWrap',
  columns: 'columns',
  dataSource: 'dataSource',
  enableAltRow: 'enableAltRow',
  enableHover: 'enableHover',
  enablePersistence: 'enablePersistence',
  enableRtl: 'enableRtl',
  filterSettings: 'filterSettings',
  gridLines: 'gridLines',
  groupSettings: 'groupSettings',
  height: 'height',
  locale: 'locale',
  pageSettings: 'pageSettings',
  printMode: 'printMode',
  query: 'query',
  rowDropSettings: 'rowDropSettings',
  rowTemplate: 'rowTemplate',
  searchSettings: 'searchSettings',
  selectedRowIndex: 'selectedRowIndex',
  selectionSettings: 'selectionSettings',
  sortSettings: 'sortSettings',
  width: 'width'
}
,{
  actionBegin: 'actionBegin',
  actionComplete: 'actionComplete',
  actionFailure: 'actionFailure',
  beforePrint: 'beforePrint',
  cellDeselected: 'cellDeselected',
  cellDeselecting: 'cellDeselecting',
  cellSelected: 'cellSelected',
  cellSelecting: 'cellSelecting',
  columnDrag: 'columnDrag',
  columnDragStart: 'columnDragStart',
  columnDrop: 'columnDrop',
  created: 'created',
  dataBound: 'dataBound',
  destroyed: 'destroyed',
  load: 'load',
  printComplete: 'printComplete',
  queryCellInfo: 'queryCellInfo',
  rowDataBound: 'rowDataBound',
  rowDeselected: 'rowDeselected',
  rowDeselecting: 'rowDeselecting',
  rowSelected: 'rowSelected',
  rowSelecting: 'rowSelecting',
  dataSourceChange: 'dataSourceChange'
}
,([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovSmVua2lucy93b3Jrc3BhY2UvX2VqMi1ncmlkLWNvbXBvbmVudHNfbWFzdGVyLTdMNU9KMkk2SFk1NExPU08yTVVaT1ZUTUlON1g2VEM2UVhWWFhEWFFKQ0JHWUxGUkxRMkEvdGhpcmQtcGFydHkvYW5ndWxhci9zcmMvZ3JpZC9ncmlkLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9KZW5raW5zL3dvcmtzcGFjZS9fZWoyLWdyaWQtY29tcG9uZW50c19tYXN0ZXItN0w1T0oySTZIWTU0TE9TTzJNVVpPVlRNSU43WDZUQzZRWFZYWERYUUpDQkdZTEZSTFEyQS90aGlyZC1wYXJ0eS9hbmd1bGFyL3NyYy9ncmlkL2dyaWQuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovSmVua2lucy93b3Jrc3BhY2UvX2VqMi1ncmlkLWNvbXBvbmVudHNfbWFzdGVyLTdMNU9KMkk2SFk1NExPU08yTVVaT1ZUTUlON1g2VEM2UVhWWFhEWFFKQ0JHWUxGUkxRMkEvdGhpcmQtcGFydHkvYW5ndWxhci9zcmMvZ3JpZC9ncmlkLmNvbXBvbmVudC50cy5HcmlkQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGVqLWdyaWQ+PC9lai1ncmlkPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7Z0JBQUE7O01BQUE7UUFBQTs7TUFBQTs7TUFBQTtRQUFBOztNQUFBOztNQUFBO1FBQUE7O01BQUE7O01BQUE7UUFBQTs7TUFBQTs7TUFBQTtRQUFBOztNQUFBOztNQUFBO1FBQUE7O01BQUE7O01BQUE7UUFBQTs7TUFBQTs7SUFBQTtLQUFBO2dCQUFBOzs7SUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
