/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/grid/grid-all.module';
import * as import2 from '@angular/common';
import * as import3 from '../../../src/grid/grid.module';
import * as import4 from '@syncfusion/ej2-grids/src/grid/actions/filter';
import * as import5 from '@syncfusion/ej2-grids/src/grid/actions/page';
import * as import6 from '@syncfusion/ej2-grids/src/grid/actions/selection';
import * as import7 from '@syncfusion/ej2-grids/src/grid/actions/sort';
import * as import8 from '@syncfusion/ej2-grids/src/grid/actions/group';
import * as import9 from '@syncfusion/ej2-grids/src/grid/actions/reorder';
import * as import10 from '@syncfusion/ej2-grids/src/grid/actions/row-reorder';
class GridAllModuleInjector extends import0.ɵNgModuleInjector<import1.GridAllModule> {
  _CommonModule_0:import2.CommonModule;
  _GridModule_1:import3.GridModule;
  _GridAllModule_2:import1.GridAllModule;
  __NgLocalization_3:import2.NgLocaleLocalization;
  _Filter_4:any;
  _Page_5:any;
  _Selection_6:any;
  _Sort_7:any;
  _Group_8:any;
  _Reorder_9:any;
  _RowDD_10:any;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_3():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_3 == null)) { (this.__NgLocalization_3 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_3;
  }
  createInternal():import1.GridAllModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._GridModule_1 = new import3.GridModule();
    this._GridAllModule_2 = new import1.GridAllModule();
    this._Filter_4 = import4.Filter;
    this._Page_5 = import5.Page;
    this._Selection_6 = import6.Selection;
    this._Sort_7 = import7.Sort;
    this._Group_8 = import8.Group;
    this._Reorder_9 = import9.Reorder;
    this._RowDD_10 = import10.RowDD;
    return this._GridAllModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.GridModule)) { return this._GridModule_1; }
    if ((token === import1.GridAllModule)) { return this._GridAllModule_2; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_3; }
    if ((token === import4.Filter)) { return this._Filter_4; }
    if ((token === import5.Page)) { return this._Page_5; }
    if ((token === import6.Selection)) { return this._Selection_6; }
    if ((token === import7.Sort)) { return this._Sort_7; }
    if ((token === import8.Group)) { return this._Group_8; }
    if ((token === import9.Reorder)) { return this._Reorder_9; }
    if ((token === import10.RowDD)) { return this._RowDD_10; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const GridAllModuleNgFactory:import0.NgModuleFactory<import1.GridAllModule> = new import0.NgModuleFactory<any>(GridAllModuleInjector,import1.GridAllModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovSmVua2lucy93b3Jrc3BhY2UvX2VqMi1ncmlkLWNvbXBvbmVudHNfbWFzdGVyLTdMNU9KMkk2SFk1NExPU08yTVVaT1ZUTUlON1g2VEM2UVhWWFhEWFFKQ0JHWUxGUkxRMkEvdGhpcmQtcGFydHkvYW5ndWxhci9zcmMvZ3JpZC9ncmlkLWFsbC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovSmVua2lucy93b3Jrc3BhY2UvX2VqMi1ncmlkLWNvbXBvbmVudHNfbWFzdGVyLTdMNU9KMkk2SFk1NExPU08yTVVaT1ZUTUlON1g2VEM2UVhWWFhEWFFKQ0JHWUxGUkxRMkEvdGhpcmQtcGFydHkvYW5ndWxhci9zcmMvZ3JpZC9ncmlkLWFsbC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
